server:
  port: 8086
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  elasticsearch:
    rest:
      uris: http://192.168.3.26:9200
  jackson:
    default-property-inclusion: non_null
  rabbitmq:
    host: 192.168.3.26
    port: 5672
    virtual-host: virtual-hang3
    username: hang3
    password: hang