server:
  port: 8092
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    host: 192.168.3.26
  rabbitmq:
    host: 192.168.3.26
    port: 5672
    virtual-host: virtual-hang3
    username: hang3
    password: hang

gmall:
  jwt:
    pubKeyPath: I:\\rsa\\rsa.pub # 公钥地址
    cookieName: GMALL_TOKEN

alipay:
  app_id: 2016091300504796
  merchant_private_key: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCMP6k1+xifgQZciDLQX8t0NMbAxXf+OJITpWXzYENlmn4S0PWbnN9eGFThJfH7CteaazRhQ1rjN35JSptghteGvxcrF4j2TXeUgC+RoMER2bUOWGJeveoWKup6ZfdH/u+0V1iduzhLdLb4CKIj6yRlEwZ7O/ZhliJy6vHc75GZjWuBEEE0UG/vfnTq5wJfqt0c60LJbsHM4+mivfMYjFaakuaFFzjn2oCkG9zCx+iqUeHaoCWtPKvJtMUTEht/gjHFdviTcDWaSPqaCWpY3Z/buzrxgjIEUtkvI7V0juJz7b3/++E+nCwDYBazQZT9Z6mX7treRcvnzy3Ex3e5fX+JAgMBAAECggEBAIophNaq4JzxjITHn9drJ5D5FPt/DTCiJjW4cPELWhnT0nNS60I7jkiyC5wpt3KqQa/cAKP4qKbCWmR1XRAAhn417esDqmeJ9U2T4kjCZrDhGd5h77aJvPvNl2Sw4qRIX3f3vFLWxyR+fGloh+J+mUIBNhddAOEt+A3hqhcO4w6yqrdb488WJni3t8MGFKZCsXK3RghnuqNUck6V8cBu5ywXGY5vlnXIliXi2bDSLj6RLvS04RHF0WZp52B8DMCOIpMKTAMKEl9D7B3ya3YYhqpiM9rHiKinWRrBLQRL9h2Izdxf2Y1T/4s25GkVLkZxczzO8k3UHoBvuiRfcxAU9yECgYEA3gXYlI3Q1mVtJwPzDdtOsRdfkWFl71MA3SgV6raNxSizB8BA49Tbv2Z+4IqKz69OyaFqsZNGxRYJdm6ok/IEcLcusSe4HGKDSuocsJmElmGlIRMaEP86ynIKrGJf2PnXsqOB8Ix8/L60MxMtYJ9ZXYPPdT4cULF8KSFxmf814P0CgYEAobYpVOm1Wn9YUZxSKUS4tF7m8deDMwo5Hk93dTvCcRO7amylpvcx8As2OaxhGumdehOemmL4zI30g2CqWO1+H1PH06XnY7vyRfG8lSurLTs2AwqSx9usdZpcmFfQ/T4KrLUrrwcY8KMq+40iiYp9of6/5SicM1pd64m84j3sdH0CgYB6e+km0zHiBWR5QLGG9HTuN8HOV1g/9p+kYmfs67c8jJ5v6T0jM5vjdK0MPQIlX0Zs7/MHcgN52RVxU80GiV6vvC8zJoFoj2R1IMChIKBHwiiyHXKk69lINC/1N/Q+pF69u3yE80xEtwR8pNjE1EQd1gjOWmyOi8u+eSfN2ECmFQKBgQCC++XmnZcDwnprQE9clgl2MBioc4QV54X0gzGjh9Arf2wi+/YBk+CjKrG1bWcKQYgIxbOGIfyc067ma3oPpe6uuVH2oT8Xjbjj5rZ1rXVtobRSKlJSCCFc8LdnvlnNhl9nHShREVKmN8QtFViQR9kTSiFtIMPE5MGGc37HUpkgkQKBgGe54jshaYi3eT3RwFlfoHBk7IuNYKhb7BZGqgyNmYh253nasZOxSYeWUc/mKooKROtVM/xIzPp9sPhYPkS8pysDbbsbPTkR1uKv7ntHlLD+LYo9iKjoRSWegQ5XC9OoRT0W2fMyqcoRAp8KUnimzDBMlUq+t97dlB3RIym5wJ6m
  alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxWS4T3AKfJpkJnivHP88gJGHJJiyjZX5JMdpTvkfvmfsitwhWJDWsD6FoBKuqcXYN0lDiCAeGa46WSjc2uGTaYazV+WckMMolvqHhjQ4X3LQJGcG35yxxBayZp/T2mzos9wU42VTjQFTIIrnNQFVv5ECNCSYuhhWR/opz/Zb9Uyij+oQHjMRZvUn883iIqiG5hl51yAJlSQrnVmJDcSeEj3uW3xfdyEZJf8N6Ydh5mQbWZWkaNeGeCVk4pJODSEdes+xLQ1Rj70uRHGx4yi7KVwK4iNDxmT8+weK+Id/CbDYLS05Hs8YmhK7CHNlAV1LP4H6SBegFF7oz6T8+NR0KQIDAQAB
  notify_url: http://30962i7s11.qicp.vip/api/order/pay/success
  return_url: http://baidu.com
  gatewayUrl: https://openapi.alipaydev.com/gateway.do
