server:
  port: 8084
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Xiaoda5580.
    url: jdbc:mysql://192.168.3.26:3306/guli_oms?useUnicode=true&characterEncoding=UTF-8&useSSL=false
  redis:
    host: 192.168.3.26
  rabbitmq:
    host: 192.168.3.26
    port: 5672
    virtual-host: virtual-hang3
    username: hang3
    password: hang
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  mapper-locations: classpath:mapper/oms/**/*.xml
